version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: tp_foyer_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tp_foyer_db
      MYSQL_USER: tp_user
      MYSQL_PASSWORD: tp_password
    ports:
      - "3306:3306"
    networks:
      - tp-foyer-network
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: moda34567/tp-foyer:1.0.0
    container_name: tp_foyer_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/tp_foyer_db
      SPRING_DATASOURCE_USERNAME: tp_user
      SPRING_DATASOURCE_PASSWORD: tp_password
    depends_on:
      - database
    ports:
      - "8082:8082"
    networks:
      - tp-foyer-network

networks:
  tp-foyer-network:

volumes:
  db_data:
